import Head from 'next/head'
import axios from 'axios';
import NoteCard from '../components/NoteCard';
import { useState } from 'react';

const Home = ({ data }) => {

  const [results, setResults] = useState(data);

  const addCard = () => {
    setResults(results.concat(
      {
        id: Math.floor(Math.random() * 100000),
        title: 'New note',
        note: 'Write something...',
        edit: true
      }
    ));
  }

  const handleChange = (title, note) => {
    axios.post('/api/posts/new', null, {
      params: {
        title: title,
        note: note
      }
    }).then(() => {
      location.reload();
    })
  }

  const handleDelete = (id) => {
    axios.delete('/api/posts/delete', {
      data: {
        id: id
      }
    }).then(() => {
      location.reload();
    })
  }

  return (
    <div className="container">
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
            Welcome to Notes App! 📝
        </h1>
        <div className="grid">
          {
            results.map((key, value) => {
              return <NoteCard data={key} handleChange={handleChange} handleDelete={handleDelete} key={key.id}/>
            })
          }
          <div className="short card add" onClick={() => { addCard(data)}}>
            <h1>➕</h1>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps() 
{
  const response = await axios.get(process.env.HOST + '/api/posts');
  const data = response.data;

  return { props: { data }}
}

export default Home